[package]
name       = "mars-types"
version    = "0.1.0"
authors    = ["larry <larry@delphidigital.io>"]
edition    = "2021"
repository = "https://github.com/mars-protocol/periphery"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
