[workspace]
members = ["contracts/*", "packages/*"]

[profile.release]
rpath = false
lto = true
overflow-checks = true

[workspace.dependencies]
cosmwasm-schema             = "1.1"
schemars                    = "0.8"