extend = [
  { path = "schema.Makefile.toml" },
]

[config]
default_to_workspace = false

[tasks.all-actions]
dependencies = [
  "generate-all-schemas",
]

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked"]
